### ISSUE TITLE
[OPENAPI] Add Discriminator to CatalogItem

### ISSUE THREAD

**Issue by TCLNA** [microsoft/Reporting-Services#174]
I'm not sure if it was intended to have "composition polymorphism" instead of inheritance, but the use of `AllOf` for inheritance has been deprecated without the use of `discriminator` (see [OpenAPI-Specification 3.0.0 # Composition and inheritance polymorphism](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#composition-and-inheritance-polymorphism).

This should fix it with few other minor tweaks:
``` yaml
CatalogItem:
    type: object
    properties: ...
    discriminator:
      propertyName: Type
```

I'm using [OpenAPITools/openapi-generator](https://github.com/OpenAPITools/openapi-generator) and it plans to make "AllOf" without "discriminator" just a simple Composition Polymorphism.

Thanks for considering this issue,
